# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CouponBell' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CouponBell

  # For Swift 3.x
  pod 'RealmSwift'

  pod 'SwiftyJSON'

  target 'CouponBellTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
